FROM node:19

WORKDIR /

COPY package*.json .

RUN npm install

COPY . . 

ENV BOT_TOKEN=MTA5MTQ2OTE1Mjc0MjU0MzQyMA.GhC1a1.9ZQmx5ZZDYmqAWOFNGpu0vfCk9vqKK_1_770ps
ENV OPENAI_APIKEY=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

CMD [ "npm", "start" ]